In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix

In [2]:
X_test = pd.read_csv('X_test.csv', delimiter=',')
X_train = pd.read_csv('X_train_balanced.csv', delimiter=',')
y_test = pd.read_csv('y_test.csv', delimiter=',')
y_train = pd.read_csv('y_train_balanced.csv', delimiter=',')

In [3]:
X_test

,Credit_Score,Idade,Tempo_Credito,Balanco,Qtd_Produtos,Possui_Cartao,Membro_Ativo,Salario_Anual,Genero_encoded,Pais_encoded
0,686,36.0,3,95848.58,2,0.0,1.0,7144694.0,1,0
1,703,35.0,1,0.00,1,1.0,1.0,14136462.0,1,0
2,730,26.0,6,0.00,1,1.0,1.0,1011687.0,1,2
3,675,33.0,6,0.00,2,0.0,1.0,1011687.0,0,0
4,754,24.0,3,121513.31,2,0.0,1.0,1011687.0,0,1
...,...,...,...,...,...,...,...,...,...,...
24922,786,37.0,4,0.00,2,0.0,1.0,1011687.0,0,2
24923,592,35.0,7,122724.50,1,1.0,1.0,17773874.0,1,0
24924,645,45.0,7,121286.32,1,1.0,1.0,869372.0,1,0
24925,567,47.0,1,126447.40,1,1.0,0.0,1011687.0,0,1
24926,725,32.0,1,0.00,2,1.0,1.0,1011687.0,1,2

In [4]:
y_test

       Churn
0        0.0
1        0.0
2        0.0
3        0.0
4        0.0
...      ...
24922    0.0
24923    0.0
24924    0.0
24925    1.0
24926    0.0

[24927 rows x 1 columns]

In [5]:
y_train

        Churn
0         1.0
1         0.0
2         1.0
3         1.0
4         1.0
...       ...
117945    1.0
117946    1.0
117947    1.0
117948    1.0
117949    1.0

[117950 rows x 1 columns]

In [6]:
X_train

,Credit_Score,Idade,Tempo_Credito,Balanco,Qtd_Produtos,Possui_Cartao,Membro_Ativo,Salario_Anual,Genero_encoded,Pais_encoded
0,711,35.000000,10,0.000000,2,1.000000,0.000000,5331178.0,1,0
1,619,33.000000,7,0.000000,2,0.000000,1.000000,1011687.0,1,0
2,841,54.000000,4,102721.490000,1,1.000000,1.000000,1011687.0,1,1
3,679,48.000000,6,125161.240000,1,1.000000,0.000000,579659.0,1,0
4,656,42.000000,6,0.000000,3,0.000000,0.000000,14233155.0,0,0
...,...,...,...,...,...,...,...,...,...,...
117945,529,43.000000,7,0.000000,1,0.514157,0.000000,1011687.0,1,2
117946,639,44.450575,7,0.000000,1,1.000000,0.725287,1011687.0,0,2
117947,541,49.890057,6,102744.063633,1,1.000000,0.000000,1011687.0,0,1
117948,593,37.911470,5,139949.785268,1,1.000000,0.000000,1011687.0,0,1
117949,733,28.402776,0,0.000000,3,0.000000,0.000000,1011687.0,0,0

Verificar o balanceamento

In [7]:
# Contar o número de exemplos de cada classe em y_trrain
train_balance = y_train.value_counts()
print("Balanceamento em y_train:")
print(train_balance)

# Contar o número de exemplos de cada classe em y_test
test_balance = y_test.value_counts()
print("\nBalanceamento em y_test:")
print(test_balance)

Balanceamento em y_train:
Churn
0.0      58975
1.0      58975
Name: count, dtype: int64

Balanceamento em y_test:
Churn
0.0      19649
1.0       5278
Name: count, dtype: int64

    O certo é entregar a base de teste desbalanceada para o modelo

In [8]:
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score

In [ ]:
# Criação de uma instancia do classificador Naive Bayes Gaussiano
naive_churn = GaussianNB()

# Treinamento do classificador usando os dados de treinamento
naive_churn.fit(X_train, y_train)

C:\Users\samco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GaussianNB()

In [12]:
# Fazer previsões para os dados de treino
y_pred_train = naive_churn.predict(X_train)

# Calcular a acuracia
accuracy = accuracy_score(y_train, y_pred_train)
print(f"Acurácia do modelo nos dados de treino:" , accuracy)

Acurácia do modelo nos dados de treino: 0.5854938533276812

Criando gráfico da matriz de confusão

In [15]:



import plotly.figure_factory as ff


conf_matrix = confusion_matrix(y_train, y_pred_train)

# Definindo nomes de classes
class_names = ['Churn', 'Não Churn']

# Plotando a matriz de confusão com Plotly
fig = ff.create_annotated_heatmap(
    z=conf_matrix,
    x=class_names,
    y=class_names,
    colorscale='Viridis',
    showscale=True
)

fig.update_layout(
    title='Matriz de Confusão - Treinamento',
    xaxis_title='Classe Predita',
    yaxis_title='Classe Verdadeira',
    font=dict(
        family="Arial",
        size=12,
        color="black"
    )
    
)