In [1]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('C:\\Users\\samco\\OneDrive\\LP\\Repositorios DEV\\EBAC_Estudos\\EBAC\\Pre_processamento_dados\\CHURN_CREDIT_MOD14.csv', delimiter=',')

df.head(10)

,Credit_Score,Pais,Genero,Idade,Tempo_Credito,Balanco,Qtd_Produtos,Possui_Cartao,Membro_Ativo,Salario_Anual,Churn
0,677,SPAIN,Male,18.0,5,134796.87,2,1.0,0.0,10787603.0,False
1,644,SPAIN,Female,18.0,7,0.00,1,0.0,1.0,10787603.0,False
2,641,SPAIN,Male,18.0,1,0.00,2,0.0,1.0,10787603.0,False
3,826,SPAIN,Male,18.0,2,0.00,2,0.0,1.0,10787603.0,False
4,774,SPAIN,Female,18.0,1,185891.54,1,1.0,0.0,10787603.0,False
5,688,SPAIN,Female,18.0,2,0.00,2,1.0,0.0,10787603.0,False
6,803,SPAIN,Male,18.0,6,0.00,1,0.0,0.0,10787603.0,True
7,578,SPAIN,Female,18.0,8,71843.15,2,0.0,1.0,10787603.0,False
8,598,SPAIN,Male,18.0,6,0.00,2,0.0,1.0,10787603.0,False
9,624,SPAIN,Female,18.0,6,0.00,2,0.0,1.0,10787603.0,False

In [3]:
# Critando uma instancia do LabelEncoder
label_encoder = LabelEncoder()

# Aplicando para a coluna "Genero"
df['Genero_encoded'] = label_encoder.fit_transform(df['Genero'])

# Aplicar o Onehot para a coluna "Pais"
df = pd.get_dummies(df, columns=['Pais'], prefix='Pais', drop_first=True) # o drop first=True é para evitar a multicolinearidade, ou seja, evitar que uma coluna seja completamente explicada por outras colunas, nesse caso, quando não for spain ou germany o valor será france, então não é necessário criar uma coluna para isso

print(df.head())

   Credit_Score  Genero  Idade  Tempo_Credito    Balanco  Qtd_Produtos  \
0           677    Male   18.0              5  134796.87             2
1           644  Female   18.0              7       0.00             1
2           641    Male   18.0              1       0.00             2
3           826    Male   18.0              2       0.00             2
4           774  Female   18.0              1  185891.54             1

   Possui_Cartao  Membro_Ativo  Salario_Anual  Churn  Genero_encoded  \
0            1.0           0.0     10787603.0  False               1
1            0.0           1.0     10787603.0  False               0
2            0.0           1.0     10787603.0  False               1
3            0.0           1.0     10787603.0  False               1
4            1.0           0.0     10787603.0  False               0

   Pais_GERMANY  Pais_SPAIN
0         False        True
1         False        True
2         False        True
3         False        True
4         False        True

TRANSFORMANDO AS COLUNAS DOS PAÍSES EM INTEIRO

In [4]:
for column in df.columns:
    if df[column].dtype == 'bool':
        df[column] = df[column].astype(int)
print(df.head())

   Credit_Score  Genero  Idade  Tempo_Credito    Balanco  Qtd_Produtos  \
0           677    Male   18.0              5  134796.87             2
1           644  Female   18.0              7       0.00             1
2           641    Male   18.0              1       0.00             2
3           826    Male   18.0              2       0.00             2
4           774  Female   18.0              1  185891.54             1

   Possui_Cartao  Membro_Ativo  Salario_Anual  Churn  Genero_encoded  \
0            1.0           0.0     10787603.0      0               1
1            0.0           1.0     10787603.0      0               0
2            0.0           1.0     10787603.0      0               1
3            0.0           1.0     10787603.0      0               1
4            1.0           0.0     10787603.0      0               0

   Pais_GERMANY  Pais_SPAIN
0             0           1
1             0           1
2             0           1
3             0           1
4             0           1

In [5]:
# Dropando a coluna "Genero" original pois ainda é categórica
df.drop('Genero', axis=1, inplace=True)

VERIFICANDO OS TIPOS DAS VARIÁVEIS

In [6]:
df.dtypes

Credit_Score        int64
Idade             float64
Tempo_Credito       int64
Balanco           float64
Qtd_Produtos        int64
Possui_Cartao     float64
Membro_Ativo      float64
Salario_Anual     float64
Churn               int64
Genero_encoded      int64
Pais_GERMANY        int64
Pais_SPAIN          int64
dtype: object

CALCULANDO A CORRELAÇÃO NOVAMENTE

In [7]:
df.corr()

,Credit_Score,Idade,Tempo_Credito,Balanco,Qtd_Produtos,Possui_Cartao,Membro_Ativo,Salario_Anual,Churn,Genero_encoded,Pais_GERMANY,Pais_SPAIN
Credit_Score,1.000000,-0.005099,-0.000574,0.006731,0.012509,-0.000922,0.011416,-0.003546,-0.024580,0.002087,0.002644,0.007817
Idade,-0.005099,1.000000,-0.013734,0.063713,-0.103867,-0.012933,0.000577,-0.029810,0.345462,-0.062781,0.094204,-0.006409
Tempo_Credito,-0.000574,-0.013734,1.000000,-0.010009,0.006161,0.003356,-0.003640,-0.002877,-0.018667,0.008811,-0.007652,0.005808
Balanco,0.006731,0.063713,-0.010009,1.000000,-0.359141,-0.017978,-0.013325,0.014596,0.129540,-0.015781,0.538309,-0.131893
Qtd_Produtos,0.012509,-0.103867,0.006161,-0.359141,1.000000,0.002109,0.039489,-0.000158,-0.211684,0.023714,-0.102636,0.027736
Possui_Cartao,-0.000922,-0.012933,0.003356,-0.017978,0.002109,1.000000,-0.024726,-0.000280,-0.021483,0.006208,-0.008175,-0.015017
Membro_Ativo,0.011416,0.000577,-0.003640,-0.013325,0.039489,-0.024726,1.000000,0.001912,-0.211063,0.035486,-0.034223,0.017031
Salario_Anual,-0.003546,-0.029810,-0.002877,0.014596,-0.000158,-0.000280,0.001912,1.000000,0.008473,-0.006709,0.026981,0.027613
Churn,-0.024580,0.345462,-0.018667,0.129540,-0.211684,-0.021483,-0.211063,0.008473,1.000000,-0.146529,0.214270,-0.050841
Genero_encoded,0.002087,-0.062781,0.008811,-0.015781,0.023714,0.006208,0.035486,-0.006709,-0.146529,1.000000,-0.044477,0.009903
Pais_GERMANY,0.002644,0.094204,-0.007652,0.538309,-0.102636,-0.008175,-0.034223,0.026981,0.214270,-0.044477,1.000000,-0.272174
Pais_SPAIN,0.007817,-0.006409,0.005808,-0.131893,0.027736,-0.015017,0.017031,0.027613,-0.050841,0.009903,-0.272174,1.000000

SEPARAÇÃO ENTRE BASE TREINO E TESTE

In [8]:
# Separar os dados em features (X) e target (y)
X = df.drop('Churn', axis=1) # Considerando que Churn é a coluna a ser predita
y = df['Churn']

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
# Separar os dados em conjuntos treino e teste
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)
# O parâmetro test_size=0.25 indica que 25% dos dados serão usados para teste e 75% para treino. O random_state=42 é usado para garantir a reprodutibilidade dos resultados, ou seja, sempre que o código for executado, a divisão dos dados será a mesma.

In [11]:
X_train

,Credit_Score,Idade,Tempo_Credito,Balanco,Qtd_Produtos,Possui_Cartao,Membro_Ativo,Salario_Anual,Genero_encoded,Pais_GERMANY,Pais_SPAIN
66440,711,35.0,10,0.00,2,1.0,0.0,5331178.0,1,0,0
59205,619,33.0,7,0.00,2,0.0,1.0,10787603.0,1,0,0
40951,841,54.0,4,102721.49,1,1.0,1.0,10787603.0,1,1,0
93972,679,48.0,6,125161.24,1,1.0,0.0,579659.0,1,0,0
86078,656,42.0,6,0.00,3,0.0,0.0,14233155.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...
6265,563,33.0,4,90727.79,2,0.0,0.0,10787603.0,1,0,1
54886,512,31.0,1,145150.28,2,1.0,0.0,10787603.0,0,0,0
76820,537,38.0,4,0.00,2,0.0,0.0,11389922.0,0,0,0
860,730,25.0,0,0.00,2,1.0,1.0,10787603.0,1,0,1
15795,635,41.0,5,0.00,1,1.0,1.0,10787603.0,0,0,1

In [12]:
X_test

,Credit_Score,Idade,Tempo_Credito,Balanco,Qtd_Produtos,Possui_Cartao,Membro_Ativo,Salario_Anual,Genero_encoded,Pais_GERMANY,Pais_SPAIN
69750,686,36.0,3,95848.58,2,0.0,1.0,7144694.0,1,0,0
67722,703,35.0,1,0.00,1,1.0,1.0,14136462.0,1,0,0
928,730,26.0,6,0.00,1,1.0,1.0,10787603.0,1,0,1
59899,675,33.0,6,0.00,2,0.0,1.0,10787603.0,0,0,0
22189,754,24.0,3,121513.31,2,0.0,1.0,10787603.0,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...
11617,786,37.0,4,0.00,2,0.0,1.0,10787603.0,0,0,1
67934,592,35.0,7,122724.50,1,1.0,1.0,17773874.0,1,0,0
90891,645,45.0,7,121286.32,1,1.0,1.0,869372.0,1,0,0
38238,567,47.0,1,126447.40,1,1.0,0.0,10787603.0,0,1,0
5252,725,32.0,1,0.00,2,1.0,1.0,10787603.0,1,0,1

In [13]:
y_train

66440    1
59205    0
40951    1
93972    1
86078    1
        ..
6265     0
54886    0
76820    0
860      0
15795    1
Name: Churn, Length: 74781, dtype: int64

In [14]:
y_test

69750    0
67722    0
928      0
59899    0
22189    0
        ..
11617    0
67934    0
90891    0
38238    1
5252     0
Name: Churn, Length: 24927, dtype: int64

BALANCEAMENTO

In [15]:
# Calcular e imprimir as porcentagens dos valores na coluna 'churn'ArithmeticError

print((df['Churn'].value_counts(normalize=True) * 100))

Churn
0    78.854254
1    21.145746
Name: proportion, dtype: float64

In [18]:
from imblearn.over_sampling import SMOTE

# Criar uma instancia do SMOTE
smote = SMOTE(random_state=42)

# Aplicar o SMOTE aos dados de treinamento (x_train e y_train)
X_train_balanced, y_train_balanced = smote.fit_resample(X_train, y_train)

# Verificar a distribuição das classes após o balanceamento
print('Distribuição das classes após o balanceamento:')
print(y_train_balanced.value_counts())

Distribuição das classes após o balanceamento:
Churn
1    58975
0    58975
Name: count, dtype: int64

In [ ]:
# Salvando as bases

y_train_balanced.to_csv('y_train_balanced.csv', index=False)
X_train_balanced.to_csv('X_train_balanced.csv', index=False)
y_test.to_csv('y_test.csv', index=False)
X_test.to_csv('X_test.csv', index=False)