# **MÓDULO 20 - Projeto de Credit Score - Naive Bayes**

No módulo 17 vocês realizaram a primeira etapa do projeto de crédito de vocês.
Então fizeram o tratamendo dos dados, balancearam as classes, transformaram as variáveis categóricas e separam base de treino e teste.
Nessa aula aplicaremos o algoritmo de naive bayes a base de vocês afim de tentarmos trazer previsões do score de crédito.

**IMPORTANTE:** Não se esqueçam de ao enviar o código de vocês para os tutores, enviarem as bases, pois como cada um de vocês realizou as alterações de tratamento indidualmente o tutor precisa ter acesso aos seus dados individuais.

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn.metrics import recall_score

Durante a aula nossa variável a ser prevista (churn) continha apenas 2 categorias, a base de vocês contém mais. O Naive Bayes pode ser aplicado para problemas de classificação com múltiplas classes da mesma forma que para problemas de classificação binária. O Naive Bayes é um algoritmo de classificação probabilístico que calcula a probabilidade de uma amostra pertencer a cada classe e seleciona a classe com a maior probabilidade como a previsão final.
Em resumo, o Naive Bayes pode ser aplicado da mesma maneira para problemas de classificação com múltiplas classes, e os mesmos princípios se aplicam em termos de treinamento, avaliação e aplicação do modelo.

# 1) Comece carregando as bases de treino (X e y) e teste (X e y).
Verifique se o número de linhas condiz, se as variáveis estão corretas sendo apenas a de score para y e as demais nas bases de X e por último, se Y está balanceada no teste.

In [31]:
#seu código aqui

X_test = pd.read_csv('X_test_balanced.csv')
y_test = pd.read_csv('y_test_balanced.csv')
X_train = pd.read_csv('X_train_balanced.csv')
y_train = pd.read_csv('y_train_balanced.csv')

In [3]:
X_test

,Unnamed: 0,Age,Gender,Income,Education,Marital Status,Number of Children,Home Ownership
0,0,25,0,55000.000000,2,1,0,1
1,1,48,0,87500.000000,3,0,1,0
2,2,26,0,55000.000000,2,0,1,0
3,3,39,0,62500.000000,2,0,2,0
4,4,35,0,90000.000000,3,0,1,0
...,...,...,...,...,...,...,...,...
82,82,26,0,53949.553051,1,1,0,1
83,83,29,0,56700.768846,1,1,0,1
84,84,30,0,50878.744390,1,0,0,0
85,85,34,1,47533.162403,0,1,0,1
86,86,25,0,55000.000000,2,0,0,0

In [32]:
y_test

    Credit Score
0              1
1              2
2              1
3              2
4              2
..           ...
82             1
83             1
84             1
85             1
86             1

[87 rows x 1 columns]

In [5]:
X_train

,Age,Gender,Income,Education,Marital Status,Number of Children,Home Ownership
0,26,0,45000.000000,1,1,0,1
1,29,0,27500.000000,0,1,0,1
2,25,0,62500.000000,2,1,0,1
3,29,0,68000.000000,3,0,2,0
4,31,1,65000.000000,2,1,0,1
...,...,...,...,...,...,...,...
247,29,0,43703.466973,1,1,0,1
248,34,1,47500.000000,1,1,0,1
249,29,0,57500.000000,1,1,0,1
250,25,0,60063.547817,2,1,0,1
251,33,1,52500.000000,0,1,0,1

In [6]:
y_train

     Credit Score
0               1
1               0
2               1
3               1
4               1
..            ...
247             1
248             1
249             1
250             1
251             1

[252 rows x 1 columns]

In [ ]:
print(y_test['Credit Score'].value_counts().sort_index())

Credit Score
0    29
1    29
2    29
Name: count, dtype: int64

# 2) Aplique o algoritmo de Naive Bayes aos dados de treinamento.

In [23]:
#seu código aqui

naive = GaussianNB()

naive.fit(X_train, y_train)

C:\Users\samco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

GaussianNB()

In [24]:
y_train_pred = naive.predict(X_train)

# 3) Faça a avaliação do modelo com os dados de treinamento.
Traga a acurácia, recall e plote a matriz de confusão. Não se esqueça de avaliar com suas palavras o desempenho do modelo, interpretando as métricas.

Dica: Para calcularmos o recall em classificação multi classe precisamos usar o atributo macro:
recall = recall_score(y_train, y_pred_train, average='macro')

In [ ]:
#seu código aqui

accuracy = accuracy_score(y_train, y_train_pred)
recall = recall_score(y_train, y_train_pred, average='macro')

print('Acurácia no conjunto de treino: ', accuracy)
print('Recall no conjunto de treino: ', recall)

Acurácia no conjunto de treino:  0.9841269841269841
Recall no conjunto de treino:  0.9841269841269842

In [27]:
import plotly.figure_factory as ff


conf_matrix = confusion_matrix(y_train, y_train_pred)

# Definindo nomes de classes
class_names = ['0', '1', '2']

# Plotando a matriz de confusão com Plotly
fig = ff.create_annotated_heatmap(
    z=conf_matrix,
    x=class_names,
    y=class_names,
    colorscale='Viridis',
    showscale=True
)

fig.update_layout(
    title='Matriz de Confusão - Treinamento',
    xaxis_title='Classe Predita',
    yaxis_title='Classe Verdadeira',
    font=dict(
        family="Arial",
        size=12,
        color="black"
    )
    
)

In [ ]:
# O modelo foi muito bem, com mais de 98% de acurácia e recall e apenasa 4 erros de classificação. Me chamou atenção os valores quase identicos de acurácia e recall.

# 4) Aplique o modelo aos dados de teste e realize a avaliação dos resultados, da mesma forma que fez acima. Não se esqueça de avaliar com as suas palavras e comparar o desempenho da base treino com a teste.

In [33]:
y_test

    Credit Score
0              1
1              2
2              1
3              2
4              2
..           ...
82             1
83             1
84             1
85             1
86             1

[87 rows x 1 columns]

In [35]:
#seu código aqui

naive.fit(X_test, y_test)

y_test_pred = naive.predict(X_test)

C:\Users\samco\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\sklearn\utils\validation.py:1352: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

In [36]:
accuracy = accuracy_score(y_test, y_test_pred)
recall = recall_score(y_test, y_test_pred, average='macro')

print('Acurácia no conjunto de teste: ', accuracy)
print('Recall no conjunto de teste: ', recall)

Acurácia no conjunto de teste:  1.0
Recall no conjunto de teste:  1.0

In [37]:

conf_matrix = confusion_matrix(y_test, y_test_pred)

# Definindo nomes de classes
class_names = ['0', '1', '2']

# Plotando a matriz de confusão com Plotly
fig = ff.create_annotated_heatmap(
    z=conf_matrix,
    x=class_names,
    y=class_names,
    colorscale='Viridis',
    showscale=True
)

fig.update_layout(
    title='Matriz de Confusão - Teste',
    xaxis_title='Classe Predita',
    yaxis_title='Classe Verdadeira',
    font=dict(
        family="Arial",
        size=12,
        color="black"
    )
    
)

In [ ]:
# O modelo lidando com a base teste teve desempenho perfeito alcançando 100% de acurácia e recall, sem nenhum erro de classificação. Isso indica que o modelo generalizou muito bem para novos dados, o que é um resultado excelente. Porém essa perfeição pode vir tamebém da pequena quantidade previsões na base de teste.

# 5) Descreva com suas palavras o projeto desenvolvido nessa atividade e qual o nosso objetivo principal ao aplicarmos o algoritmo de naive bayes a base de crédito.
Utilize pelo menos 4 linhas.

Dica: Caso você ainda esteja tendo dificuldade em visualizar a aplicação dos projetos e objetivo, consulte seus tutores!

Foi muito interessante desenvolver esse projeto e ver a evolução de tudo o que aprendemos, em que começamos tratando a base para deixar os dados que seriam importantes, dividindo as base de treino e teste e balanceando, e depois criando o modelo pra fazer seu treinamento e teste naquela base que desenvolvemos. O objetivo principal do algoritmo naive bayes é justamente ser usado para classificar as coisas, nesse caso de score de crédito ele foi perfeito em classificar qual tipo de score cada cliente receberia com as informações que possuia da base, ou seja, ele entendeu o motivo do porquê cada cliente receber tal score e pôde usar essa compreensão pra classificar novos clientes com precisão.